name: Prevent Commits
on: push
          
jobs:
  process_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for Azure Key
      run: |
        # Search for the string "azure_key121" in all files
        if grep -r -q "azure_key121" .; then
            echo "Found 'azure_key121' in one or more files. Commit will not be successful."
            exit 1
        else
            echo "No occurrence of 'azure_key121' found. Commit is allowed."
        fi


    