name: Replace Content
on: push
          
jobs:
  process_files:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List all files
      run: |
        # Use PowerShell command to list all files (excluding directories) and save the output to 'files.txt'
        Get-ChildItem -File -Recurse -Exclude 'files.txt', '*.yml', 'replacements.txt' | ForEach-Object { $_.FullName } > files.txt

    - name: Read replacements from replacements.txt
      id: read_replacements
      run: |
        $replacements = @{}
        Get-Content "replacements.txt" | ForEach-Object {
          $parts = $_ -split ':', 2
          $key = $parts[0].Trim()
          $value = $parts[1].Trim()
          $replacements[$key] = $value
        }
        Write-Host "REPLACEMENTS=$(ConvertTo-Json $replacements)" >> $GITHUB_ENV

    - name: Process Files
      run: |
        # Read the 'files.txt' file line by line and process each file
        Get-Content files.txt | ForEach-Object {
          # Do something with each file (e.g., echo its name and path)
          echo "File Name: $_"

          # Read the replacements from the environment variable
          $replacements = ConvertFrom-Json $env:REPLACEMENTS

          # Process the file for each key-value pair in the replacements
          foreach ($key in $replacements.Keys) {
            $value = $replacements[$key]
            (Get-Content $_) -replace $key, $value | Set-Content $_
          }
        }

    - name: Delete files.txt
      run: |
        # Use PowerShell command to delete the 'files.txt' file
        Remove-Item -Path files.txt

    - name: Commit and push changes
      run: |
        git config --local user.name "sahil0823"
        git config --local user.email "sahil.sharma@amantyatech.com"
        git commit -am "Updated file content via GitHub Actions"
        git push https://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@github.com/sahil0823/prehook-check.git