name: Replace Content
on: push
          
jobs:
  process_files:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List all files
      run: |
        # Use 'find' command to list all files (excluding directories) and save the output to 'files.txt'
        find . -type f > files.txt

    - name: Process Files
      run: |
        # Read the 'files.txt' file line by line and process each file
        while IFS= read -r file; do
          # Do something with each file (e.g., echo its name and path)
          echo "File Name: $file"
        done < files.txt

    - name: Delete files.txt
      run: |
        # Use 'rm' command to delete the 'files.txt' file
        rm files.txt
          