name: Replace Content
on:
  push:
    branches:
      - main  # Modify this branch name if needed

jobs:
  replace_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace file content
        run: |
          # Replace file1.txt content
          sed -i 's/azure_key/sahil/g' config.json
      - name: Commit and push changes
        run: |
          git config --local user.name "sahil0823"
          git config --local user.email "sahil.sharma@amantyatech.com
          git commit -am "Updated file content via GitHub Actions"
          git push
