name: Replace Content
on: push
          
jobs:
  process_files:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List all files
      run: |
        # Use PowerShell command to list all files (excluding directories) and save the output to 'files.txt'
        Get-ChildItem -File -Recurse -Exclude 'files.txt', '*.yml', 'replacements.json' | ForEach-Object { $_.FullName } > files.txt

    - name: Process Files
      run: |
        # Retrieve the replacements JSON from the repository
        $jsonContent = Get-Content -Raw -Path replacements.json | ConvertFrom-json
        echo "keys : $jsonContent.Keys"
        foreach ($key in $jsonContent.Keys) {
          $value = $jsonContent[$key]
          echo "key : $key, value : $value"
          Write-Host "Key: $key, Value: $value"
        }
          

        # Read the 'files.txt' file line by line and process each file
        Get-Content files.txt | ForEach-Object {
          # Do something with each file (e.g., echo its name and path)

          foreach ($key in $jsonContent.Keys) {
              echo "File Name: $_"
              echo "inner loop" 
              $value = $jsonContent[$key]
              echo "key : $key"
              echo "value : $value"
              # (Get-Content $_) -replace "$value", "$key" | Set-Content $_
          }

          # (Get-Content $_) -replace 'azure_key121', 'placeholder' | Set-Content $_
        }

    - name: Delete files.txt
      run: |
        # Use PowerShell command to delete the 'files.txt' file
        Remove-Item -Path files.txt

    - name: Commit and push changes
      run: |
        git config --local user.name "sahil0823"
        git config --local user.email "sahil.sharma@amantyatech.com"
        git commit -am "Updated file content via GitHub Actions"
        git push https://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@github.com/sahil0823/prehook-check.git