name: Replace Content
on: push
          
jobs:
  process_files:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Replace keys in files
        run: |
          # Retrieve the replacements JSON from the repository
          $jsonContent = Get-Content -Raw -Path replacements.json | ConvertFrom-Json

          # Loop through each file in the repository (excluding the "replacements.json" file)
          $files = Get-ChildItem -Recurse | Where-Object { $_.Name -ne "replacements.json" }
          foreach ($file in $files) {
            # Read the content of the file
            $content = Get-Content -Raw -Path $file.FullName

            # Replace the placeholders with their corresponding values
            $jsonContent.PSObject.Properties | ForEach-Object {
              $placeholder = $_.Name
              $value = $_.Value
              $content = $content -replace $placeholder, $value
            }

            # Overwrite the file with the updated content
            $content | Set-Content -Path $file.FullName
          }

      - name: Commit and push changes
        run: |
          git config --local user.name "sahil0823"
          git config --local user.email "sahil.sharma@amantyatech.com"
          git commit -am "Updated file content via GitHub Actions"
          git push https://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@github.com/sahil0823/prehook-check.git