name: Replace File Content
on:
  push:
    branches:
      - main

jobs:
  replace_files:
    runs-on: windows
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Replace the content in file
        run: |
          PLACEHOLDER="[REDACTED]"
          find . -type f -name 'config.json' -exec sed -i "s/azure_key/${PLACEHOLDER}/g" {} + 
      - name: Commit and push changes
        run: |
          git config --local user.email "sahil.sharma@amantyatech.com"
          git config --local user.name "sahil0823"
          git commit -am "Replace file content via GitHub Action"
          git push
